# Preprocessing Practice

## Load the dataset and import preprocessing tools

This first section imports the scikit-learn helpers used throughout the notebook and loads the Iris dataset. `load_iris` returns the feature matrix `x` and target labels `y`.

The goal here is simply to get a small, clean dataset that makes preprocessing steps easy to demonstrate.

## What this notebook demonstrates

This notebook walks through the most common preprocessing steps in scikit-learn:

- splitting data into training and test sets
- scaling numeric features with standardization and min-max normalization
- encoding categorical features with ordinal encoding and one-hot encoding

Each block below shows the raw code first, then the result of applying the preprocessing step.

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Split the data into training and test sets

`train_test_split` separates the dataset into two parts: one for training the preprocessing step and model, and one for testing how well the processing generalizes to unseen data.

Using `random_state=42` makes the split reproducible, so the same rows go into the same sets each time the notebook is run.

In [3]:
x, y = load_iris(return_X_y=True)

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [5]:
scalar = StandardScaler()
x_train_scaled = scalar.fit_transform(x_train)
x_test_scaled = scalar.transform(x_test)

## Standardize the numeric features

`StandardScaler` transforms each feature so it has mean 0 and standard deviation 1. This is useful when features are on different scales because many machine learning algorithms work better when the inputs are centered and scaled.

The scaler is fit only on `x_train`, then reused to transform `x_test`. That avoids leaking information from the test set into the training process.

In [6]:
import numpy as np
(x_train-np.mean(x_train, axis=0)) / np.std(x_train, axis=0  )

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.58505976,  0.78699794,  0.4227026 ],
       [ 0.72020757,  0.08570939,  1.01622064,  0.8231577 ],
       [ 0.96400139, -0.13788033,  0.38585821,  0.28921757],
       [ 1.69538284,  1.20365799,  1.3600547 ,  1.75755292],
       [-0.13307079, -0.36147005,  0.27124686,  0.15573254],
       [ 2.18297047, -0.13788033,  1.64658307,  1.22361279],
       [-0.2549677 , -0.13788033,  0.44316389,  0.4227026 ],
       [-0.86445224,  0.98006827, -1.33331205, -1.31260282],
       [ 2.30486738, -0.58505976,  1.70388875,  1.09012776],
       [-0.01117388, -0.80864948,  0.21394119, -0.24472256],
       [-0.74255534,  0.75647855, -1.33331205, -1.31260282],
       [-0.98634915,  0.98006827, -1.39061772, -1.17911778],
       [-0.86445224,  1.65083742, -1.04678367, -1.04563275],
       [-0.98634915, -2.37377751, -0.12989286, -0.24472256],
       [ 0.59831066, -0.80864948,  0.67238659,  0.8231577 ],
       [-1.23014297,  0.75647855, -1.04678367, -1.31260282],
       [-0.98634915, -0.13788033, -1.2187007 , -1.31260282],
       [-0.86445224,  0.53288883, -1.16139502, -0.91214772],
       [-0.2549677 , -0.80864948,  0.27124686,  0.15573254],
       [-0.86445224,  0.75647855, -1.27600637, -1.31260282],
       [-0.13307079, -0.13788033,  0.27124686,  0.02224751],
       [ 2.30486738,  1.65083742,  1.70388875,  1.35709783],
       [-1.47393679,  0.30929911, -1.33331205, -1.31260282],
       [ 0.47641375, -0.36147005,  0.32855254,  0.15573254],
       [-0.13307079, -1.25582892,  0.72969227,  1.09012776],
       [-0.37686461,  2.5451963 , -1.33331205, -1.31260282],
       [ 0.23261993, -0.13788033,  0.61508092,  0.8231577 ],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993, -1.92659808,  0.15663551, -0.24472256],
       [-0.49876152, -0.13788033,  0.44316389,  0.4227026 ],
       [ 0.47641375,  0.75647855,  0.95891497,  1.49058286],
       [-0.37686461, -1.70300836,  0.15663551,  0.15573254],
       [-0.49876152,  1.87442714, -1.16139502, -1.04563275],
       [-0.98634915, -1.70300836, -0.24450422, -0.24472256],
       [ 0.72020757, -0.80864948,  0.90160929,  0.95664273],
       [-0.98634915,  0.53288883, -1.33331205, -1.31260282],
       [-0.98634915,  0.30929911, -1.4479234 , -1.31260282],
       [-0.37686461, -1.47941864,  0.04202416, -0.11123753],
       [ 1.08589829, -0.13788033,  0.72969227,  0.68967267],
       [-1.10824606,  0.08570939, -1.27600637, -1.31260282],
       [-0.01117388, -0.58505976,  0.78699794,  1.62406789],
       [-0.98634915,  0.75647855, -1.27600637, -1.31260282],
       [-0.98634915,  0.98006827, -1.2187007 , -0.77866269],
       [ 0.11072303,  0.30929911,  0.61508092,  0.8231577 ],
       [-0.86445224, -1.25582892, -0.41642124, -0.11123753],
       [ 1.32969211,  0.30929911,  1.130832  ,  1.49058286],
       [ 0.23261993, -0.80864948,  0.78699794,  0.55618763],
       [ 0.35451684, -1.0322392 ,  1.07352632,  0.28921757],
       [ 2.30486738, -0.13788033,  1.3600547 ,  1.49058286],
       [-0.37686461, -1.25582892,  0.15663551,  0.15573254],
       [-1.7177306 , -0.36147005, -1.33331205, -1.31260282],
       [-1.83962751, -0.13788033, -1.50522907, -1.44608785],
       [ 0.23261993, -1.92659808,  0.72969227,  0.4227026 ],
       [ 1.69538284,  0.30929911,  1.30274902,  0.8231577 ],
       [-1.47393679,  0.08570939, -1.27600637, -1.31260282],
       [-0.86445224,  0.98006827, -1.33331205, -1.17911778],
       [-1.7177306 , -0.13788033, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.67238659,  0.4227026 ],
       [ 0.59831066,  0.75647855,  1.07352632,  1.62406789],
       [-1.47393679,  0.75647855, -1.33331205, -1.17911778],
       [ 1.2077952 , -0.13788033,  1.01622064,  1.22361279],
       [ 0.59831066,  0.53288883,  1.30274902,  1.75755292],
       [-1.35203988,  0.30929911, -1.39061772, -1.31260282],
       [ 0.35451684, -0.36147005,  0.55777524,  0.28921757],
       [ 0.84210448, -0.58505976,  0.50046957,  0.4227026 ],
       [ 0.47641375, -0.58505976,  0.61508092,  0.8231577 ],
       [ 1.45158902,  0.30929911,  0.55777524,  0.28921757],
       [ 0.72020757,  0.30929911,  0.90160929,  1.49058286],
       [-0.86445224,  1.65083742, -1.2187007 , -1.31260282],
       [ 1.32969211,  0.08570939,  0.95891497,  1.22361279],
       [ 0.11072303, -0.13788033,  0.27124686,  0.4227026 ],
       [ 0.84210448, -0.13788033,  0.84430362,  1.09012776],
       [-0.13307079, -1.0322392 , -0.12989286, -0.24472256],
       [-0.74255534, -0.80864948,  0.09932984,  0.28921757],
       [ 0.35451684, -0.13788033,  0.50046957,  0.28921757],
       [-1.5958337 , -1.70300836, -1.39061772, -1.17911778],
       [ 0.96400139, -0.36147005,  0.50046957,  0.15573254],
       [-0.37686461, -1.0322392 ,  0.38585821,  0.02224751],
       [-0.62065843,  1.4272477 , -1.27600637, -1.31260282],
       [-0.2549677 , -0.13788033,  0.21394119,  0.15573254],
       [ 1.81727975, -0.36147005,  1.47466605,  0.8231577 ],
       [ 1.08589829,  0.53288883,  1.130832  ,  1.22361279],
       [-0.86445224,  1.4272477 , -1.27600637, -1.04563275],
       [-1.10824606, -1.47941864, -0.24450422, -0.24472256],
       [ 1.08589829,  0.53288883,  1.130832  ,  1.75755292],
       [ 1.69538284, -0.13788033,  1.18813767,  0.55618763],
       [-1.10824606,  1.20365799, -1.33331205, -1.44608785],
       [ 1.08589829,  0.08570939,  1.07352632,  1.62406789],
       [-1.10824606, -0.13788033, -1.33331205, -1.31260282],
       [ 1.32969211,  0.08570939,  0.67238659,  0.4227026 ],
       [ 1.93917666, -0.58505976,  1.3600547 ,  0.95664273],
       [ 0.59831066, -0.36147005,  1.07352632,  0.8231577 ],
       [-0.13307079, -0.58505976,  0.21394119,  0.15573254],
       [ 0.84210448, -0.13788033,  1.01622064,  0.8231577 ],
       [ 0.59831066, -1.70300836,  0.38585821,  0.15573254],
       [ 0.72020757, -0.36147005,  0.32855254,  0.15573254],
       [-0.2549677 , -0.58505976,  0.67238659,  1.09012776],
       [ 0.11072303, -0.13788033,  0.78699794,  0.8231577 ],
       [-0.49876152,  0.75647855, -1.16139502, -1.31260282],
       [ 0.35451684, -0.58505976,  0.15663551,  0.15573254],
       [-1.10824606, -1.25582892,  0.44316389,  0.68967267],
       [-0.01117388,  2.09801686, -1.4479234 , -1.31260282],
       [-0.01117388, -1.0322392 ,  0.15663551,  0.02224751],
       [ 1.57348593, -0.13788033,  1.24544335,  1.22361279]])

## Check the scaling math manually

This cell recomputes standardization with NumPy so you can see what `StandardScaler` is doing under the hood.

The formula is:

$\displaystyle z = \frac{x - \mu}{\sigma}$

where `x` is the original value, `μ` is the feature mean, and `σ` is the feature standard deviation.

In [7]:
x_train_scaled

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.58505976,  0.78699794,  0.4227026 ],
       [ 0.72020757,  0.08570939,  1.01622064,  0.8231577 ],
       [ 0.96400139, -0.13788033,  0.38585821,  0.28921757],
       [ 1.69538284,  1.20365799,  1.3600547 ,  1.75755292],
       [-0.13307079, -0.36147005,  0.27124686,  0.15573254],
       [ 2.18297047, -0.13788033,  1.64658307,  1.22361279],
       [-0.2549677 , -0.13788033,  0.44316389,  0.4227026 ],
       [-0.86445224,  0.98006827, -1.33331205, -1.31260282],
       [ 2.30486738, -0.58505976,  1.70388875,  1.09012776],
       [-0.01117388, -0.80864948,  0.21394119, -0.24472256],
       [-0.74255534,  0.75647855, -1.33331205, -1.31260282],
       [-0.98634915,  0.98006827, -1.39061772, -1.17911778],
       [-0.86445224,  1.65083742, -1.04678367, -1.04563275],
       [-0.98634915, -2.37377751, -0.12989286, -0.24472256],
       [ 0.59831066, -0.80864948,  0.67238659,  0.8231577 ],
       [-1.23014297,  0.75647855, -1.04678367, -1.31260282],
       [-0.98634915, -0.13788033, -1.2187007 , -1.31260282],
       [-0.86445224,  0.53288883, -1.16139502, -0.91214772],
       [-0.2549677 , -0.80864948,  0.27124686,  0.15573254],
       [-0.86445224,  0.75647855, -1.27600637, -1.31260282],
       [-0.13307079, -0.13788033,  0.27124686,  0.02224751],
       [ 2.30486738,  1.65083742,  1.70388875,  1.35709783],
       [-1.47393679,  0.30929911, -1.33331205, -1.31260282],
       [ 0.47641375, -0.36147005,  0.32855254,  0.15573254],
       [-0.13307079, -1.25582892,  0.72969227,  1.09012776],
       [-0.37686461,  2.5451963 , -1.33331205, -1.31260282],
       [ 0.23261993, -0.13788033,  0.61508092,  0.8231577 ],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993, -1.92659808,  0.15663551, -0.24472256],
       [-0.49876152, -0.13788033,  0.44316389,  0.4227026 ],
       [ 0.47641375,  0.75647855,  0.95891497,  1.49058286],
       [-0.37686461, -1.70300836,  0.15663551,  0.15573254],
       [-0.49876152,  1.87442714, -1.16139502, -1.04563275],
       [-0.98634915, -1.70300836, -0.24450422, -0.24472256],
       [ 0.72020757, -0.80864948,  0.90160929,  0.95664273],
       [-0.98634915,  0.53288883, -1.33331205, -1.31260282],
       [-0.98634915,  0.30929911, -1.4479234 , -1.31260282],
       [-0.37686461, -1.47941864,  0.04202416, -0.11123753],
       [ 1.08589829, -0.13788033,  0.72969227,  0.68967267],
       [-1.10824606,  0.08570939, -1.27600637, -1.31260282],
       [-0.01117388, -0.58505976,  0.78699794,  1.62406789],
       [-0.98634915,  0.75647855, -1.27600637, -1.31260282],
       [-0.98634915,  0.98006827, -1.2187007 , -0.77866269],
       [ 0.11072303,  0.30929911,  0.61508092,  0.8231577 ],
       [-0.86445224, -1.25582892, -0.41642124, -0.11123753],
       [ 1.32969211,  0.30929911,  1.130832  ,  1.49058286],
       [ 0.23261993, -0.80864948,  0.78699794,  0.55618763],
       [ 0.35451684, -1.0322392 ,  1.07352632,  0.28921757],
       [ 2.30486738, -0.13788033,  1.3600547 ,  1.49058286],
       [-0.37686461, -1.25582892,  0.15663551,  0.15573254],
       [-1.7177306 , -0.36147005, -1.33331205, -1.31260282],
       [-1.83962751, -0.13788033, -1.50522907, -1.44608785],
       [ 0.23261993, -1.92659808,  0.72969227,  0.4227026 ],
       [ 1.69538284,  0.30929911,  1.30274902,  0.8231577 ],
       [-1.47393679,  0.08570939, -1.27600637, -1.31260282],
       [-0.86445224,  0.98006827, -1.33331205, -1.17911778],
       [-1.7177306 , -0.13788033, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.67238659,  0.4227026 ],
       [ 0.59831066,  0.75647855,  1.07352632,  1.62406789],
       [-1.47393679,  0.75647855, -1.33331205, -1.17911778],
       [ 1.2077952 , -0.13788033,  1.01622064,  1.22361279],
       [ 0.59831066,  0.53288883,  1.30274902,  1.75755292],
       [-1.35203988,  0.30929911, -1.39061772, -1.31260282],
       [ 0.35451684, -0.36147005,  0.55777524,  0.28921757],
       [ 0.84210448, -0.58505976,  0.50046957,  0.4227026 ],
       [ 0.47641375, -0.58505976,  0.61508092,  0.8231577 ],
       [ 1.45158902,  0.30929911,  0.55777524,  0.28921757],
       [ 0.72020757,  0.30929911,  0.90160929,  1.49058286],
       [-0.86445224,  1.65083742, -1.2187007 , -1.31260282],
       [ 1.32969211,  0.08570939,  0.95891497,  1.22361279],
       [ 0.11072303, -0.13788033,  0.27124686,  0.4227026 ],
       [ 0.84210448, -0.13788033,  0.84430362,  1.09012776],
       [-0.13307079, -1.0322392 , -0.12989286, -0.24472256],
       [-0.74255534, -0.80864948,  0.09932984,  0.28921757],
       [ 0.35451684, -0.13788033,  0.50046957,  0.28921757],
       [-1.5958337 , -1.70300836, -1.39061772, -1.17911778],
       [ 0.96400139, -0.36147005,  0.50046957,  0.15573254],
       [-0.37686461, -1.0322392 ,  0.38585821,  0.02224751],
       [-0.62065843,  1.4272477 , -1.27600637, -1.31260282],
       [-0.2549677 , -0.13788033,  0.21394119,  0.15573254],
       [ 1.81727975, -0.36147005,  1.47466605,  0.8231577 ],
       [ 1.08589829,  0.53288883,  1.130832  ,  1.22361279],
       [-0.86445224,  1.4272477 , -1.27600637, -1.04563275],
       [-1.10824606, -1.47941864, -0.24450422, -0.24472256],
       [ 1.08589829,  0.53288883,  1.130832  ,  1.75755292],
       [ 1.69538284, -0.13788033,  1.18813767,  0.55618763],
       [-1.10824606,  1.20365799, -1.33331205, -1.44608785],
       [ 1.08589829,  0.08570939,  1.07352632,  1.62406789],
       [-1.10824606, -0.13788033, -1.33331205, -1.31260282],
       [ 1.32969211,  0.08570939,  0.67238659,  0.4227026 ],
       [ 1.93917666, -0.58505976,  1.3600547 ,  0.95664273],
       [ 0.59831066, -0.36147005,  1.07352632,  0.8231577 ],
       [-0.13307079, -0.58505976,  0.21394119,  0.15573254],
       [ 0.84210448, -0.13788033,  1.01622064,  0.8231577 ],
       [ 0.59831066, -1.70300836,  0.38585821,  0.15573254],
       [ 0.72020757, -0.36147005,  0.32855254,  0.15573254],
       [-0.2549677 , -0.58505976,  0.67238659,  1.09012776],
       [ 0.11072303, -0.13788033,  0.78699794,  0.8231577 ],
       [-0.49876152,  0.75647855, -1.16139502, -1.31260282],
       [ 0.35451684, -0.58505976,  0.15663551,  0.15573254],
       [-1.10824606, -1.25582892,  0.44316389,  0.68967267],
       [-0.01117388,  2.09801686, -1.4479234 , -1.31260282],
       [-0.01117388, -1.0322392 ,  0.15663551,  0.02224751],
       [ 1.57348593, -0.13788033,  1.24544335,  1.22361279]])

In [8]:

x_min = np.min(x_train, axis=0)
x_max = np.max(x_train, axis=0)
x_train_scaled = (x_train - x_min) / (x_max - x_min)
x_test_scaled = (x_test - x_min) / (x_max - x_min)

## Apply min-max normalization

This section rescales every feature into the range from 0 to 1.

The formula is:

$\displaystyle x' = \frac{x - x_{min}}{x_{max} - x_{min}}$

This is different from standardization: instead of centering around a mean of 0, it compresses values into a fixed interval based on the minimum and maximum values seen in the training data.

In [9]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

## Encode categorical features

The next examples use the `car` and `adult` datasets from OpenML to show how categorical variables are transformed into numeric form.

First, `OrdinalEncoder` is used when the categories have a natural order. Then `OneHotEncoder` is used when the categories are nominal and should not be treated as ordered values.

In [12]:
data = fetch_openml('car', as_frame=True)
data.frame.head()

c:\Users\pc\Desktop\Dev\MLE\Scikit-Practice\.venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

  buying  maint doors persons lug_boot safety binaryClass
0  vhigh  vhigh     2       2    small    low           P
1  vhigh  vhigh     2       2    small    med           P
2  vhigh  vhigh     2       2    small   high           P
3  vhigh  vhigh     2       2      med    low           P
4  vhigh  vhigh     2       2      med    med           P

In [18]:
columns_to_encode = ['lug_boot', 'safety']
encoder = OrdinalEncoder(
    categories=[
        ['small', 'med', 'big'],
        ['low', 'med', 'high'],
    ]
)
data.frame[columns_to_encode] = encoder.fit_transform(data.frame[columns_to_encode])

In [19]:
data

{'data':      buying  maint  doors persons lug_boot safety
 0     vhigh  vhigh      2       2    small    low
 1     vhigh  vhigh      2       2    small    med
 2     vhigh  vhigh      2       2    small   high
 3     vhigh  vhigh      2       2      med    low
 4     vhigh  vhigh      2       2      med    med
 ...     ...    ...    ...     ...      ...    ...
 1723    low    low  5more    more      med    med
 1724    low    low  5more    more      med   high
 1725    low    low  5more    more      big    low
 1726    low    low  5more    more      big    med
 1727    low    low  5more    more      big   high

 [1728 rows x 6 columns],
 'target': 0       P
 1       P
 2       P
 3       P
 4       P
        ..
 1723    N
 1724    N
 1725    P
 1726    N
 1727    N
 Name: binaryClass, Length: 1728, dtype: category
 Categories (2, str): ['N', 'P'],
 'frame':      buying  maint  doors persons  lug_boot  safety binaryClass
 0     vhigh  vhigh      2       2       0.0     0.0           P
 1     vhigh  vhigh      2       2       0.0     1.0           P
 2     vhigh  vhigh      2       2       0.0     2.0           P
 3     vhigh  vhigh      2       2       1.0     0.0           P
 4     vhigh  vhigh      2       2       1.0     1.0           P
 ...     ...    ...    ...     ...       ...     ...         ...
 1723    low    low  5more    more       1.0     1.0           N
 1724    low    low  5more    more       1.0     2.0           N
 1725    low    low  5more    more       2.0     0.0           P
 1726    low    low  5more    more       2.0     1.0           N
 1727    low    low  5more    more       2.0     2.0           N

 [1728 rows x 7 columns],
 'categories': None,
 'feature_names': ['buying',
  'maint',
  'doors',
  'persons',
  'lug_boot',
  'safety'],
 'target_names': ['binaryClass'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nBinarized version of the original data set (see version 1). The multi-class target feature is converted to a two-class nominal target feature by re-labeling the majority class as positive ('P') and all others as negative ('N'). Originally converted by Quan Sun.\n\nDownloaded from openml.org.",
 'details': {'id': '991',
  'name': 'car',
  'version': '2',
  'description_version': '1',
  'format': 'ARFF',
  'upload_date': '2014-10-04T22:44:31',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/53525/car.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0991/dataset_991.pq',
  'file_id': '53525',
  'default_target_attribute': 'binaryClass',
  'tag': ['Automobiles',
   'Data Science',
   'derived',
   'mythbusting_1',
   'study_1',
   'study_15',
   'study_20',
   'study_41',
   'study_7'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:17:54',
  'md5_checksum': '49c57b793eef1b8e55f297e5e019fdbf'},
 'url': 'https://www.openml.org/d/991'}

In [20]:
data = fetch_openml('adult', as_frame=True)
data.frame.head()

c:\Users\pc\Desktop\Dev\MLE\Scikit-Practice\.venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
data.occupation.value_counts()

AttributeError: occupation

In [27]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_values = encoder.fit_transform(data.frame[['occupation', 'education']])
new_cols = encoder.get_feature_names_out(['occupation', 'education'])
encoded_df = pd.DataFrame(encoded_values, columns=new_cols)

In [28]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'education_10th', 'education_11th',
       'education_12th', 'education_1st-4th', 'education_5th-6th',
       'education_7th-8th', 'education_9th', 'education_Assoc-acdm',
       'education_Assoc-voc', 'education_Bachelors',
       'education_Doctorate', 'education_HS-grad', 'education_Masters',
       'education_Preschool', 'education_Prof-school',
       'education_Some-college'], dtype=object)

In [29]:
df_encoded = pd.concat([data.frame, encoded_df], axis=1)
df_encoded.drop(columns=['occupation', 'education'], inplace=True)  

data_final = pd.concat([data.frame, encoded_df], axis=1)
data_final.drop(columns=['occupation', 'education'], inplace=True)

In [30]:
data_final

,age,workclass,fnlwgt,education-num,marital-status,relationship,race,sex,capitalgain,capitalloss,...,education_9th,education_Assoc-acdm,education_Assoc-voc,education_Bachelors,education_Doctorate,education_HS-grad,education_Masters,education_Preschool,education_Prof-school,education_Some-college
0,2,State-gov,77516,13,Never-married,Not-in-family,White,Male,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3,Self-emp-not-inc,83311,13,Married-civ-spouse,Husband,White,Male,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Private,215646,9,Divorced,Not-in-family,White,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,3,Private,234721,7,Married-civ-spouse,Husband,Black,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,Private,338409,13,Married-civ-spouse,Wife,Black,Female,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,13,Divorced,Not-in-family,White,Female,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
48838,4,NaN,321403,9,Widowed,Other-relative,Black,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
48839,2,Private,374983,13,Married-civ-spouse,Husband,White,Male,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
48840,2,Private,83891,13,Divorced,Own-child,Asian-Pac-Islander,Male,2,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
48841,1,Self-emp-inc,182148,13,Married-civ-spouse,Husband,White,Male,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0